# Étape 1 : build Vue
FROM node:18 AS builder
WORKDIR /app
COPY . .
RUN yarn install && yarn build

# Étape 2 : servir avec nginx
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
